[project]
name = "mf07-language"
version = "1.2.2"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pyyaml",
]

[project.scripts]
mf = "src.commands.main:main"
